## 6. Numpy

In [1]:
import numpy as np

arr = np.array([1,2,3,4])
print(arr)
print(type(arr))

[1 2 3 4]
<class 'numpy.ndarray'>


#### 6.1. 0으로 초기화 된 배열 (zeros)

In [2]:
arr = np.zeros((3,3))
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


#### 6.2. 빈 값으로 만들어진 배열 (empty)
    - 어차피 다 채워줄 것 같을 때 empty 사용

In [3]:
arr = np.empty((4,4))
print(arr)

[[6.23042070e-307 4.67296746e-307 1.69121096e-306 9.34609111e-307]
 [1.11256817e-306 1.06811422e-306 1.42417221e-306 1.11260619e-306]
 [8.90094053e-307 1.86919378e-306 1.06809792e-306 1.37962456e-306]
 [1.69111861e-306 1.78020169e-306 1.37961777e-306 7.56599807e-307]]


#### 6.3. 1로 가득찬 배열을 만든다 (ones)
    - 속도를 위해서 실수형 사용

In [4]:
arr = np.ones((3,3))
print(arr)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


#### 6.4. 배열의 생성(arange)

In [5]:
arr = np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


#### 6.5. ndarray 배열의 모양(shape), 차수(ndim), 데이터 타입 확인(dtype)

In [6]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [7]:
# 배열의 모양
print(arr.shape)

(2, 3)


In [8]:
# 배열의 차원
print(arr.ndim)

2


In [9]:
# 데이터 타입
print(arr.dtype)

int32


In [10]:
# 데이터 타입 바꾸기
arr_float = arr.astype(np.float64)
print(arr_float.dtype)

float64


In [11]:
# string을 int로 바꾸기
arr_str = np.array(['1','2','3'])
print(arr_str.dtype)

<U1


In [12]:
arr_int = arr_str.astype(np.int64)
print(arr_int.dtype)

int64


#### 6.6. ndarray 배열의 연산(add, substract, multiply, divide)

In [13]:
arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[5,6],[7,8]])

In [14]:
# 더하기
print(arr1 + arr2)

[[ 6  8]
 [10 12]]


In [15]:
# numpy 기능을 사용하여 더하기 (add, multiply, divide)
print(np.add(arr1, arr2))

[[ 6  8]
 [10 12]]


In [16]:
# 곱하기
print(arr1 * arr2)

[[ 5 12]
 [21 32]]


In [17]:
# numpy 기능을 사용하여 곱하기
print(np.multiply(arr1, arr2))

[[ 5 12]
 [21 32]]


#### 6.7. ndarray 배열 슬라이싱 하기

In [18]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


#### arr이 2차원 배열이므로 2차원으로 슬라이싱해야한다
    ':2'  = Index 0부터 2까지 (2는 포함 X) 
    '1:3' = Index 1부터 3까지 (3는 포함 X)

In [19]:
arr_1 = arr[:2,1:3]
print(arr_1)

[[2 3]
 [5 6]]


In [20]:
## arr 배열에서 (0,2)의 요소를 출력함
print(arr[0,2])

3


In [21]:
# arr 배열에서 (0,2) (1,0) (2,1)의 요소를 출력함
print(arr[[0,1,2], [2,0,1]])

[3 4 8]


In [22]:
idx = arr > 3
print(idx)

[[False False False]
 [ True  True  True]
 [ True  True  True]]


In [23]:
# idx에서 True되는 요소만 배열로 출력되서 나옴
print(arr[idx])

[4 5 6 7 8 9]


#### 6.8. Readwine에 대한 CSV를 불러온다
    - delimiter = ';' : 구별자 ';'로 데이터를 구분한다
    - skiprows = 1 : 첫줄은 header이므로 무시한다

In [24]:
redwine = np.loadtxt(fname = 'winequality-red.csv', delimiter = ';', skiprows = 1)
print(redwine)

[[ 7.4    0.7    0.    ...  0.56   9.4    5.   ]
 [ 7.8    0.88   0.    ...  0.68   9.8    5.   ]
 [ 7.8    0.76   0.04  ...  0.65   9.8    5.   ]
 ...
 [ 6.3    0.51   0.13  ...  0.75  11.     6.   ]
 [ 5.9    0.645  0.12  ...  0.71  10.2    5.   ]
 [ 6.     0.31   0.47  ...  0.66  11.     6.   ]]


In [25]:
# 총 합계 (sum)
print(redwine.sum())

152084.78194


In [26]:
# 평균 (mean)
print(redwine.mean())

7.926036165311652


In [27]:
# 축 (axis)
# 축 0의 합계
print('축 0의 합계: \n',redwine.sum(axis=0))
print('\n축 0의 평균: \n', redwine.mean(axis=0))

축 0의 합계: 
 [13303.1       843.985     433.29     4059.55      139.859   25384.
 74302.       1593.79794  5294.47     1052.38    16666.35     9012.     ]

축 0의 평균: 
 [ 8.31963727  0.52782051  0.27097561  2.5388055   0.08746654 15.87492183
 46.46779237  0.99674668  3.3111132   0.65814884 10.42298311  5.63602251]


In [28]:
# 슬라이싱 
# (: = 모든 행 , 0 = 첫번째 열)
print(redwine[:,0])

[7.4 7.8 7.8 ... 6.3 5.9 6. ]


In [29]:
# 첫번째 행의 평균
print(redwine[ :,0].mean())

8.31963727329581


In [30]:
# 각 열마다 max 값을 출력
print(redwine.max(axis= 0))

[ 15.9       1.58      1.       15.5       0.611    72.      289.
   1.00369   4.01      2.       14.9       8.     ]


In [31]:
# 각 열마다 min 값을 출력
print(redwine.min(axis=0))

[4.6     0.12    0.      0.9     0.012   1.      6.      0.99007 2.74
 0.33    8.4     3.     ]
